# Site settings
title: Geoinquietos Valencia
email: geoinquietosvlc@gmail.com
author: Geoinquietos VLC
description: "Comunidad de entusiastas de la información geográfica en Valencia."
baseurl: ""
url: "http://geoinquietosvlc.github.io"
google_analytics:
animated: false
show_related_posts: true


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/geoinquietosvlc/geoinquietosvlc.github.io/

permalink: pretty
paginate: 3
sass:
  sass_dir:          _sass
  style:            :compressed

gems:
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  - scope:
      type: post
